baseURL = "https://2lovecode.github.io/"
languageCode = "en-us"
title = "2lovecode"

[params]
  logo      = "/avatar.jpg"
  github    = "https://github.com/2lovecode/"
  email     = "liu546hao@163.com"
