baseURL = 'https://2lovecode.github.io/'
languageCode = 'zh-CN'
title = '字母狂想'
theme = 'smigle'
[[menu.main]]
  identifier = "home"
  name = "首页"
  url = "/"
  weight = 1

[[menu.main]]
  identifier = "about"
  name = "关于"
  url = "/about/"
  weight = 2

[[menu.main]]
  identifier = "posts"
  name = "文章"
  url = "/posts/"
  weight = 3

[[menu.main]]
  identifier = "categories"
  name = "分类"
  url = "/categories/"
  weight = 4

[[menu.main]]
  identifier = "tags"
  name = "标签"
  url = "/tags/"
  weight = 5

[[menu.main]]
  identifier = "rss"
  name = "RSS"
  url = "/index.xml"
  weight = 6
